version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: beto
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
  